Шахматная доска с использованием position: absolute|relative и коорди…
fd1-44-17-group/stimorolmenthol pull request #5
Opened 2017-09-14 19:25 UTC by stimorolmenthol

@fd1-44-17 Please review. Thanks

2017-09-15 06:26 UTC, fd1-44-17 requested changes

2017-09-15 06:26 UTC, fd1-44-17 commented on dz/chess2/chess2.html
> +        <div class="kletka kletka-bl" style="left: 0"><img src="img/ladya.png"></div>
изображения должны быть вынесены в background
inline-стилей быть не должно - все вынесено в классы.

2017-09-15 06:26 UTC, fd1-44-17 commented on dz/chess2/chess2.html
> +        <div class="kletka kletka-bl" style="left: 0"><img src="img/ladya.png"></div>
никакого нарезания изображений. Все с использованием спрайтов!

2017-09-19 21:10 UTC, stimorolmenthol commented
@fd1-44-17 fixed. Please review.

2017-09-22 04:54 UTC, fd1-44-17 approved these changes

2017-09-22 04:54 UTC, merged